language: php

php:
    - 7.2
    - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - SYMFONY_VERSION=4.3.*

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit;