language: php

php:
    - 7.4
    - 8.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=5.1.*
  - SYMFONY_VERSION=6.*

matrix:
  exclude:
    - php: 7.4
      env: SYMFONY_VERSION=4.0.*
    - php: 7.4
      env: SYMFONY_VERSION=4.1.*

before_install:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then composer require "codeclimate/php-test-reporter:dev-master@dev" --no-update; fi;

install:
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi;

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.4" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;
