mediamonks_media_image_stream:
  path: /media/image/stream/{id}/{width}/{height}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::imageStreamAction
  methods: [ GET ]
  requirements:
    id: \d+

mediamonks_media_image_download:
  path: /media/image/download/{id}/{width}/{height}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::imageDownloadAction
  methods: [ GET ]
  requirements:
    id: \d+

mediamonks_media_image_redirect:
  path: /media/image/redirect/{id}/{width}/{height}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::imageRedirectAction
  methods: [ GET ]
  requirements:
    id: \d+

mediamonks_media_stream:
  path: /media/stream/{id}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::streamAction
  methods: [ GET ]
  requirements:
    id: \d+

mediamonks_media_download:
  path: /media/download/{id}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::downloadAction
  methods: [ GET ]
  requirements:
    id: \d+

mediamonks_media_redirect:
  path: /media/redirect/{id}
  controller: MediaMonks\SonataMediaBundle\Controller\MediaController::redirectAction
  methods: [ GET ]
  requirements:
    id: \d+